version: '3.9'

services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dbkarting
      MYSQL_ROOT_PASSWORD: 0210
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile.backend
    depends_on:
      - db
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dbkarting
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0210

  frontend:
    build:
      context: ./rmKarting
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80" # Cambiado de 5173 a 80 porque usas nginx y quieres servir contenido estático

volumes:
  db_data:
